# Generated by Django 2.1.5 on 2019-01-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='identifier',
            new_name='identifier',
        ),
    ]
