# Generated by Django 2.1.5 on 2019-01-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190114_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='identifier',
            new_name='username',
        ),
    ]
